controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\FormRegister;
use app\models\Users;
use app\models\User;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\data\ActiveDataProvider;
use app\models\Talentos;
use app\models\Filtro;
use app\models\FormPreregistro;



class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    
    
    public function actionUsuario(){
        return $this->render("/talentos/create");
    }
    public function actionAdministrador(){
        return $this->render("/talentos/index");
        
    }
    
    
    
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
    
 
    

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
         
        $modelo = new Filtro();
        
         
         if ($modelo->load(Yii::$app->request->post())){
             
          $texto_buscar_genero = substr($modelo->textoBuscar, 0, -4); 
        
             
            $query = Talentos::find()
            ->orWhere(['particular' => $modelo->particular])
            ->orWhere(['empresa' => $modelo->empresa])
            ->andFilterWhere(['like', 'profesion', $texto_buscar_genero])
            ->orderBy(['apellidos' => SORT_DESC]);
            
         }else{
            $query = Talentos::find()
            ->orderBy(['apellidos' => SORT_DESC]);
              
         }
         
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);
            return $this->render('index',['dataProvider' => $dataProvider,'modelo'=>$modelo]);
    }   

    /**
     * Login action.
     *
     * @return Response|string
     */
 public function actionLogin()
    {
       
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
      
        $model = new LoginForm();
       
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            if(User::isUserAdmin(Yii::$app->user->identity->id)){
                return $this->redirect(["/talentos"]);
            }else{
                return $this->redirect(["/talentos/perfil"]);
            }
        }else{
            $model->password = '';
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();
       
       return $this->goHome();
    }

    public function actionMostrartalento($id)
    {
      
        $query = Talentos::find()
             ->andWhere(['id' => $id]);
          
       
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            
        ]);
        return $this->render('perfil',['dataProvider' => $dataProvider]);
    
      
        
    }            
     public function actionQuesonlanzaderas()
    {
      
        return $this->render('queson_lanzaderas');
 
    }            
        public function actionAutorizacion()
    {
      
        return $this->render('autorizacion');
 
    } 
      public function actionPreregistro()
    {
        $mensaje="";
        $model = new FormPreregistro(); 
         if ($model->load(Yii::$app->request->post())) {
             $mensaje = "Tu petición ha sido solicitada. En breve recibiras un correo con tus datos de acceso a nuestra Web.";
         }
        return $this->render('form_autorizo',['model' => $model,'msg'=>$mensaje]);
 
    } 
    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }
    
    
    
    
     private function randKey($str='', $long=0)
    {
        $key = null;
        $str = str_split($str);
        $start = 0;
        $limit = count($str)-1;
        for($x=0; $x<$long; $x++)
        {
            $key .= $str[rand($start, $limit)];
        }
        return $key;
    }
  
 public function actionConfirm()
 {
    $table = new Users;
    if (Yii::$app->request->get())
    {
   
        //Obtenemos el valor de los parámetros get
        $id = Html::encode($_GET["id"]);
        $authKey = $_GET["authKey"];
    
        if ((int) $id)
        {
            //Realizamos la consulta para obtener el registro
            $model = $table
            ->find()
            ->where("id=:id", [":id" => $id])
            ->andWhere("authKey=:authKey", [":authKey" => $authKey]);
 
            //Si el registro existe
            if ($model->count() == 1)
            {
                $activar = Users::findOne($id);
                $activar->activate = 1;
                if ($activar->update())
                {
                    echo "Enhorabuena registro llevado a cabo correctamente, redireccionando ...";
                    echo "<meta http-equiv='refresh' content='8; ".Url::toRoute("site/login")."'>";
                }
                else
                {
                    echo "Ha ocurrido un error al realizar el registro, redireccionando ...";
                    echo "<meta http-equiv='refresh' content='8; ".Url::toRoute("site/login")."'>";
                }
             }
            else //Si no existe redireccionamos a login
            {
                return $this->redirect(["site/login"]);
            }
        }
        else //Si id no es un número entero redireccionamos a login
        {
            return $this->redirect(["site/login"]);
        }
    }
 }
 

    /**
     * Displays about page.
     *
     * @return string
     */
 public function actionRegister()
 {
  //Creamos la instancia con el model de validación
  $model = new FormRegister;
   
  //Mostrará un mensaje en la vista cuando el usuario se haya registrado
  $msg = null;
   
  //Validación mediante ajax
//  if ($model->load(Yii::$app->request->post()) && Yii::$app->request->isAjax)
//        {
//            Yii::$app->response->format = Response::FORMAT_JSON;
//            return ActiveForm::validate($model);
//        }
   
  //Validación cuando el formulario es enviado vía post
  //Esto sucede cuando la validación ajax se ha llevado a cabo correctamente
  //También previene por si el usuario tiene desactivado javascript y la
  //validación mediante ajax no puede ser llevada a cabo
  if ($model->load(Yii::$app->request->post()))
  {
      
   if($model->validate())
   {
    //Preparamos la consulta para guardar el usuario
    $table = new Users;
    $table->username = $model->username;
    $table->email = $model->email;
    $table->tipo = "invitado";
    //Encriptamos el password
    $table->password = crypt($model->password, Yii::$app->params["salt"]);
    //Creamos una cookie para autenticar al usuario cuando decida recordar la sesión, esta misma
    //clave será utilizada para activar el usuario
    $table->authKey = $this->randKey("abcdef0123456789", 200);
    //Creamos un token de acceso único para el usuario
    $table->accessToken = $this->randKey("abcdef0123456789", 200);
     
    //Si el registro es guardado correctamente
    if ($table->insert())
    {
     //Nueva consulta para obtener el id del usuario
     //Para confirmar al usuario se requiere su id y su authKey
     $user = $table->find()->where(["email" => $model->email])->one();
     $id = urlencode($user->id);
     $authKey = urlencode($user->authKey);
      
     $subject = "Confirmar registro";
     $body = "<h1>Haga click en el siguiente enlace para finalizar tu registro</h1>";
     $body .= "<a href='http://127.0.0.1/.../index.php?r=site/confirm&id=".$id."&authKey=".$authKey."'>Confirmar</a>";
      
     //Enviamos el correo
     Yii::$app->mailer->compose()
     ->setTo($user->email)
     ->setFrom([Yii::$app->params["adminEmail"] => Yii::$app->params["title"]])
     ->setSubject($subject)
     ->setHtmlBody($body)
     ->send();
     
     $model->username = null;
     $model->email = null;
     $model->password = null;
     $model->password_repeat = null;
     
     $msg = "Enhorabuena, ahora sólo falta que confirmes tu registro en tu cuenta de correo";
    }
    else
    {
     $msg = "Ha ocurrido un error al llevar a cabo tu registro";
    }
     
   }
   else
   {
    $model->getErrors();
   }
  }
  return $this->render("register", ["model" => $model, "msg" => $msg]);
 }
 
 


}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use app\models\User;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <style>
        .titulo{
            font-size: 2.5em;
        }
    </style>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
//     if(Yii::$app->user->isGuest){
            NavBar::begin([
                'brandLabel' => Yii::$app->name,
                 'options' => [
                    'class' => 'titulo',
                ],
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => [
                    // ['label' => 'Home', 'url' => ['/site/index'],'visible'=>Yii::$app->user->isGuest],
                     
                    ['label' => 'Talentos', 'url' => ['/talentos'],'visible'=>!Yii::$app->user->isGuest && User::isUserAdmin(Yii::$app->user->identity->getId())],
                    ['label' => 'Registro', 'url' => ['/site/register'],'visible'=>!Yii::$app->user->isGuest && User::isUserAdmin(Yii::$app->user->identity->getId())],
                    ['label' => 'Regístrate', 'url' => ['/site/preregistro'],'visible'=>Yii::$app->user->isGuest],
                   // ['label' => 'Home', 'url' => ['/site/index'],'visible'=>Yii::$app->user->isGuest],
                    //['label' => 'Talentos', 'url' => ['/talentos'],'visible'=>User::isUserAdmin(Yii::$app->user->identity->getId())],
                    //['label' => 'Registrate', 'url' => ['/site/register'],'visible'=>Yii::$app->user->isGuest],
                  //  ['label' => 'Contact', 'url' => ['/site/contact']],
                    
//                     $id = $identity->getId();
                    Yii::$app->user->isGuest ? (
                        ['label' => 'Entrar', 'url' => ['/site/login']]
                    ) : (
                        '<li>'
                        . Html::beginForm(['/site/logout'], 'post')
                        . Html::submitButton(
                            'Logout (' . Yii::$app->user->identity->username . ')',
                            ['class' => 'btn btn-link logout']
                        )
                        . Html::endForm()
                        . '</li>'
                    )
                ],
            ]);
            NavBar::end();
   
//     }
//     if(User::isUserAdmin(Yii::$app->user->identity->getId()) || (!Yii::$app->user->isGuest)){
//            NavBar::begin([
//                'brandLabel' => Yii::$app->name,
//                'brandUrl' => Yii::$app->homeUrl,
//                'options' => [
//                    'class' => 'navbar-inverse navbar-fixed-top',
//                ],
//            ]);
//            echo Nav::widget([
//                'options' => ['class' => 'navbar-nav navbar-right'],
//                'items' => [
//                    ['label' => 'Home', 'url' => ['/site/index']],
//                    ['label' => 'Talentos', 'url' => ['/talentos']],
//                    //['label' => 'Registro', 'url' => ['/site/register']],
//        //            ['label' => 'Contact', 'url' => ['/site/contact']],
//                    
//                    
//                    Yii::$app->user->isGuest ? (
//                        ['label' => 'Login', 'url' => ['/site/login']]
//                    ) : (
//                        '<li>'
//                        . Html::beginForm(['/site/logout'], 'post')
//                        . Html::submitButton(
//                            'Logout (' . Yii::$app->user->identity->username . ')',
//                            ['class' => 'btn btn-link logout']
//                        )
//                        . Html::endForm()
//                        . '</li>'
//                    )
//                ],
//            ]);
//            NavBar::end();
//    
//     }
    

     
     
     
    ?>

    <div>
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="">
    <div class="container">

    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main_rober.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use app\models\User;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
//     if(Yii::$app->user->isGuest){
            NavBar::begin([
                'brandLabel' => Yii::$app->name,
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => [
                    ['label' => 'Home', 'url' => ['/site/index'],'visible'=>Yii::$app->user->isGuest],
                    ['label' => 'Talentos', 'url' => ['/talentos'],'visible'=>!Yii::$app->user->isGuest && User::isUserAdmin(Yii::$app->user->identity->getId())],
                    ['label' => 'Registro', 'url' => ['/site/register'],'visible'=>!Yii::$app->user->isGuest && User::isUserAdmin(Yii::$app->user->identity->getId())],
        //            ['label' => 'Contact', 'url' => ['/site/contact']],
                    
//                     $id = $identity->getId();
                    Yii::$app->user->isGuest ? (
                        ['label' => 'Login', 'url' => ['/site/login']]
                    ) : (
                        '<li>'
                        . Html::beginForm(['/site/logout'], 'post')
                        . Html::submitButton(
                            'Logout (' . Yii::$app->user->identity->username . ')',
                            ['class' => 'btn btn-link logout']
                        )
                        . Html::endForm()
                        . '</li>'
                    )
                ],
            ]);
            NavBar::end();
   
//     }
//     if(User::isUserAdmin(Yii::$app->user->identity->getId()) || (!Yii::$app->user->isGuest)){
//            NavBar::begin([
//                'brandLabel' => Yii::$app->name,
//                'brandUrl' => Yii::$app->homeUrl,
//                'options' => [
//                    'class' => 'navbar-inverse navbar-fixed-top',
//                ],
//            ]);
//            echo Nav::widget([
//                'options' => ['class' => 'navbar-nav navbar-right'],
//                'items' => [
//                    ['label' => 'Home', 'url' => ['/site/index']],
//                    ['label' => 'Talentos', 'url' => ['/talentos']],
//                    //['label' => 'Registro', 'url' => ['/site/register']],
//        //            ['label' => 'Contact', 'url' => ['/site/contact']],
//                    
//                    
//                    Yii::$app->user->isGuest ? (
//                        ['label' => 'Login', 'url' => ['/site/login']]
//                    ) : (
//                        '<li>'
//                        . Html::beginForm(['/site/logout'], 'post')
//                        . Html::submitButton(
//                            'Logout (' . Yii::$app->user->identity->username . ')',
//                            ['class' => 'btn btn-link logout']
//                        )
//                        . Html::endForm()
//                        . '</li>'
//                    )
//                ],
//            ]);
//            NavBar::end();
//    
//     }
    

     
     
     
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>