controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\FormRegister;
use app\models\Users;
use app\models\User;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\data\ActiveDataProvider;
use app\models\Talentos;
use app\models\Filtro;
use app\models\FormPreregistro;



class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    
    
    public function actionUsuario(){
        return $this->render("/talentos/create");
    }
    public function actionAdministrador(){
        return $this->render("/talentos/index");
        
    }
    
    
    
    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
    
 
    

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
         
        $modelo = new Filtro();
        
         
         if ($modelo->load(Yii::$app->request->post())){
             
          $texto_buscar_genero = substr($modelo->textoBuscar, 0, -4); 
        
             
            $query = Talentos::find()
            ->orWhere(['particular' => $modelo->particular])
            ->orWhere(['empresa' => $modelo->empresa])
            ->andFilterWhere(['like', 'profesion', $texto_buscar_genero])
            ->orderBy(['apellidos' => SORT_DESC]);
            
         }else{
            $query = Talentos::find()
            ->orderBy(['apellidos' => SORT_DESC]);
              
         }
         
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);
            return $this->render('index',['dataProvider' => $dataProvider,'modelo'=>$modelo]);
    }   

    /**
     * Login action.
     *
     * @return Response|string
     */
 public function actionLogin()
    {
       
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
      
        $model = new LoginForm();
       
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            if(User::isUserAdmin(Yii::$app->user->identity->id)){
                return $this->redirect(["/talentos"]);
            }else{
                return $this->redirect(["/talentos/perfil"]);
            }
        }else{
            $model->password = '';
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();
       
       return $this->goHome();
    }

    public function actionMostrartalento($id)
    {
      
        $query = Talentos::find()
             ->andWhere(['id' => $id]);
          
       
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            
        ]);
        return $this->render('perfil',['dataProvider' => $dataProvider]);
    
      
        
    }            
     public function actionQuesonlanzaderas()
    {
      
        return $this->render('queson_lanzaderas');
 
    }            
        public function actionAutorizacion()
    {
      
        return $this->render('autorizacion');
 
    } 
      public function actionPreregistro()
    {
        $mensaje="";
        $model = new FormPreregistro(); 
         if ($model->load(Yii::$app->request->post())) {
             $mensaje = "Tu petición ha sido solicitada. En breve recibiras un correo con tus datos de acceso a nuestra Web.";
         }
        return $this->render('form_autorizo',['model' => $model,'msg'=>$mensaje]);
 
    } 
    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }
    
    
    
    
     private function randKey($str='', $long=0)
    {
        $key = null;
        $str = str_split($str);
        $start = 0;
        $limit = count($str)-1;
        for($x=0; $x<$long; $x++)
        {
            $key .= $str[rand($start, $limit)];
        }
        return $key;
    }
  
 public function actionConfirm()
 {
    $table = new Users;
    if (Yii::$app->request->get())
    {
   
        //Obtenemos el valor de los parámetros get
        $id = Html::encode($_GET["id"]);
        $authKey = $_GET["authKey"];
    
        if ((int) $id)
        {
            //Realizamos la consulta para obtener el registro
            $model = $table
            ->find()
            ->where("id=:id", [":id" => $id])
            ->andWhere("authKey=:authKey", [":authKey" => $authKey]);
 
            //Si el registro existe
            if ($model->count() == 1)
            {
                $activar = Users::findOne($id);
                $activar->activate = 1;
                if ($activar->update())
                {
                    echo "Enhorabuena registro llevado a cabo correctamente, redireccionando ...";
                    echo "<meta http-equiv='refresh' content='8; ".Url::toRoute("site/login")."'>";
                }
                else
                {
                    echo "Ha ocurrido un error al realizar el registro, redireccionando ...";
                    echo "<meta http-equiv='refresh' content='8; ".Url::toRoute("site/login")."'>";
                }
             }
            else //Si no existe redireccionamos a login
            {
                return $this->redirect(["site/login"]);
            }
        }
        else //Si id no es un número entero redireccionamos a login
        {
            return $this->redirect(["site/login"]);
        }
    }
 }
 

    /**
     * Displays about page.
     *
     * @return string
     */
 public function actionRegister()
 {
  //Creamos la instancia con el model de validación
  $model = new FormRegister;
   
  //Mostrará un mensaje en la vista cuando el usuario se haya registrado
  $msg = null;
   
  //Validación mediante ajax
//  if ($model->load(Yii::$app->request->post()) && Yii::$app->request->isAjax)
//        {
//            Yii::$app->response->format = Response::FORMAT_JSON;
//            return ActiveForm::validate($model);
//        }
   
  //Validación cuando el formulario es enviado vía post
  //Esto sucede cuando la validación ajax se ha llevado a cabo correctamente
  //También previene por si el usuario tiene desactivado javascript y la
  //validación mediante ajax no puede ser llevada a cabo
  if ($model->load(Yii::$app->request->post()))
  {
      
   if($model->validate())
   {
    //Preparamos la consulta para guardar el usuario
    $table = new Users;
    $table->username = $model->username;
    $table->email = $model->email;
    $table->tipo = "invitado";
    //Encriptamos el password
    $table->password = crypt($model->password, Yii::$app->params["salt"]);
    //Creamos una cookie para autenticar al usuario cuando decida recordar la sesión, esta misma
    //clave será utilizada para activar el usuario
    $table->authKey = $this->randKey("abcdef0123456789", 200);
    //Creamos un token de acceso único para el usuario
    $table->accessToken = $this->randKey("abcdef0123456789", 200);
     
    //Si el registro es guardado correctamente
    if ($table->insert())
    {
     //Nueva consulta para obtener el id del usuario
     //Para confirmar al usuario se requiere su id y su authKey
     $user = $table->find()->where(["email" => $model->email])->one();
     $id = urlencode($user->id);
     $authKey = urlencode($user->authKey);
      
     $subject = "Confirmar registro";
     $body = "<h1>Haga click en el siguiente enlace para finalizar tu registro</h1>";
     $body .= "<a href='http://127.0.0.1/.../index.php?r=site/confirm&id=".$id."&authKey=".$authKey."'>Confirmar</a>";
      
     //Enviamos el correo
     Yii::$app->mailer->compose()
     ->setTo($user->email)
     ->setFrom([Yii::$app->params["adminEmail"] => Yii::$app->params["title"]])
     ->setSubject($subject)
     ->setHtmlBody($body)
     ->send();
     
     $model->username = null;
     $model->email = null;
     $model->password = null;
     $model->password_repeat = null;
     
     $msg = "Enhorabuena, ahora sólo falta que confirmes tu registro en tu cuenta de correo";
    }
    else
    {
     $msg = "Ha ocurrido un error al llevar a cabo tu registro";
    }
     
   }
   else
   {
    $model->getErrors();
   }
  }
  return $this->render("register", ["model" => $model, "msg" => $msg]);
 }
 
 


}

views/site/_post.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;

$Apelnomb = $model->nombre." ".$model->apellidos;
$rutaFoto = '@web/img/'.$model->lanzadera.'/'.$model->apellidos.$model->nombre.$model->id.'.png';

?>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<div class="col-md-12" style="margin-top: 60px;padding:0 30px">
    <div class="perfil" style="margin: 40px 240px; padding:20px">
        <div class="row no-gutters">
            <div class="col-md-4" style="text-align:center">
                <img src="<?=Url::to($rutaFoto)?>" class="card-img" alt="" width="160px;" height="180px" style="border-radius: 5%;">
             </div>
            <div class="col-md-8" style="padding:10px 30px 0px; text-align:right">
                <div class="card-body">
                    <p style="font-size:1.7em; font-weight:bold"><?= $Apelnomb ?></p>
                    <p style="color:#D62020; font-size:1.7em; font-weight:bold; font-family:serif;"><?= $model->profesion ?></p>
                </div>
            </div>
        </div>
        <div class="row no-gutters">
            <div class="col-md-12" style="padding: 16px 30px; text-align:justify;">
                <p><?= $model->sobremi ?></p>
            </div>
        </div>
        <div class="row no-gutters">
            <div class="col-md-12" style="padding: 0 30px; text-align:right;">
                <!--<button type="button" class="botonver btn" style="width: 160px; background-color: #247386; "><a href="file:///C:/Users/veroc/OneDrive/Escritorio/COSINAS/lanzadera_empleo/perfil_mostrar.html" style="text-decoration:none; color:white; font-weight:bold;">Ver</a></button>-->
                  <?=Html::a(Yii::t('app','Ver'), ['/site/mostrartalento', 'id' => $model->id],['class' => 'botonver btn','style' => 'width:160px;text-decoration: none;color: white; font-weight: bold;background-color: #247386']) ?>
            </div>
        </div>
    </div>
</div>

views/site/_post_copia.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;

$Apelnomb = $model->nombre." ".$model->apellidos;
$rutaFoto = '@web/img/'.$model->lanzadera.'/'.$model->apellidos.$model->nombre.$model->id.'.png';

?>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<div class="perfiles col-md-12" style="margin-top: 60px;padding:0 60px">
    <div class="perfil" style="margin: 40px 240px; padding:20px">
        <div class="row no-gutters">
            <div class="col-md-4" style="text-align:center">
                <img src="<?=Url::to($rutaFoto)?>" class="card-img" alt="" width="110px;" style="border-radius: 5%;">
             </div>
            <div class="col-md-8" style="padding:50px 50px 0px; text-align:right">
                <div class="card-body">
                    <p style="font-size:1.7em; font-weight:bold"><?= $Apelnomb ?></p>
                    <p style="color:#DC7534; font-size:1.7em; font-weight:bold; font-family:serif;">Profesión pues se hace lo que se puede</p>
                </div>
            </div>
        </div>
        <div class="row no-gutters">
            <div class="col-md-12" style="padding: 16px 50px; text-align:justify;">
                <p><?= $model->sobremi ?></p>
            </div>
        </div>
        <div class="row no-gutters">
            <div class="col-md-12" style="padding: 0 50px; text-align:right;">
                <!--<button type="button" class="botonver btn" style="width: 160px; background-color: #247386; "><a href="file:///C:/Users/veroc/OneDrive/Escritorio/COSINAS/lanzadera_empleo/perfil_mostrar.html" style="text-decoration:none; color:white; font-weight:bold;">Ver</a></button>-->
                  <?=Html::a(Yii::t('app','Ver'), ['/site/mostrartalento', 'id' => $model->id],['class' => 'botonver btn','style' => 'width:160px;text-decoration: none;color: white; font-weight: bold;background-color: #247386']) ?>
            </div>
        </div>
    </div>
</div>

views/site/_post_todo.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\web\Link;



$Apelnomb = $model->nombre." ".$model->apellidos;
$rutaFoto = '@web/img/'.$model->lanzadera.'/'.$model->apellidos.$model->nombre.$model->id.'.png';
$linkedin = $model->linkedin;
//echo $linkedin;
//exit;

?>
       <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

        <div class="col-md-12" style="padding:0 120px;">
            <div class="col-md-4">
		<img src="<?=Url::to($rutaFoto)?>" alt="candidato" height="220px;" width="180px;" style="border-radius: 3%; margin-left: 40px" />
            </div>
            <div class="col-md-8" style=" margin-top: 40px; text-align: right">
                <p style="font-size:1.7em; font-weight:bold"><?= $Apelnomb ?></p>
                <p style="color:#D62020; font-size:1.7em; font-weight:bold; font-family:serif;"><?= $model->profesion ?></p>
                <p style="font-size:1.7em; font-weight:bold">Lanzadera de Medio Cudeyo</p>
            </div>
	</div>

	<div class="col-md-12" style="padding: 50px 140px;text-align: justify;">
            <p style="font-size: 1.3em; font-weight: bold;">ALGO SOBRE MI</p>
            <p style="font-size: 1.2em; font-weight: bold"><?= $model->sobremi?></p>
            <p style="font-size: 1.3em; font-weight: bold; padding-top: 40px;">MI CARTA DE PRESENTACION</p>
            <p style="font-size: 1.2em;"><?= $model->carta ?></p>
	</div>
	
	<div class="col-md-12" style="padding: 40px 140px;">
            <p style="font-weight: bold; padding-bottom: 20px;">ME PUEDES CONTACTAR AQUÍ:</p>
            <div class="row">
                <div class="col-md-6" style="text-align: center">
                    <!--<p style="font-size: 1.3em; font-weight: bold; text-align: left;"><?= $model->email?></p>-->
                    <i class="fas fa-envelope fa-4x" style="color: #337AB7"></i><p style="font-size: 20px;"><?= $model->email?></p>
                    <i class="fas fa-phone-square fa-4x" style="color: #337AB7"></i><p style="font-size: 20px"><?= $model->telefono?></p>
                </div>
                <div class="col-md-6" style="text-align: center">
                    <a href="<?= $linkedin ?>" target="_blank"><i class="fab fa-linkedin fa-4x"></i></a><span><p style="font-size: 20px;">Linkedin</p>
                    <a href="<?= $model->web ?>" target="_blank"><i class="fab fa-chrome fa-4x"></i></a><p style="font-size: 20px;">Visita mi Web</p>
                </div>        
            </div>
        </div>        

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ListView;
use yii\data\ActiveDataProvider;
use yii\widgets\ActiveForm;
//$tipo = ['Particular'=>'Particular','Empresa'=>'Empresa'];
$url = Yii::getAlias("@web") . '/img/';
?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
	<!--<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">-->
	<title>Listado Perfiles</title>
	<style type="text/css">
                main{
                        
                }
		.ayto{
			padding-top: 10px;
		}
		.logo{
			padding-top: 10px;
		}
		.camino{
			
		}
		.cabecera{
			margin-bottom: 60px;
			padding: 40px 0;
		}
		.pie{
			height: 220px;
			margin-top: 120px;
		}
		.gobierno{
			text-align: right;
			padding-top: 60px;
		}
		.emcan{
			text-align: center;
			padding-top: 90px;
		}
		.cantabria{
			padding-top: 30px;
		}
		.textopie{
			padding: 80px 20px;
		}
		p.enelpie{
			font-weight: bold;
			font-size: 1.2em;
		}
		.fondo{
/*			background-image: '../../web/img/casacorpas3.png';*/
			background-size: cover;
			width: 100%;
			height: 100%;
			position: relative;
		}
		.fondo:before{
			content: "";
			width: 100%;
			height: 100%;
			background-color: #cccccc;
			position: absolute;
			top: 0;
			left: 0;
			opacity: 0.8;
		}
                .desmarcado {
                   /*border: 4px solid black;*/
                     opacity: 0.5;;
                }
               
</style>
</head>
<body>
    
    <div class="col-md-12" style="padding-bottom:140px; padding-top:80px">
        <div class="camino col-md-4">
                <img src="<?=Url::to('@web/img/lg_camino.png')?>" alt="camino" width="390px" />
        </div>

        <div class="ayto col-md-4">
                <p style="font-weight:bold; font-size:1.3em; text-align:center; padding: 44px 28px 0;">Lanzadera de Empleo y Emprendimiento Solidario del Ayuntamiento de Medio Cudeyo</p>
        </div>

        <div class="ayto col-md-2">
                <img src="<?=Url::to('@web/img/lg_ayuntamiento.png')?>" alt="lanzaderas" width="156px" />
        </div>

        <div class="logo col-md-2 col-12">
                <a href="https://www.cantabriaemprendedora.es/es/lanzaderas-cantabria-que-son-y-como-participar" target="_blank"><img src="<?=Url::to('@web/img/lg_lanzaderas3.png')?>" alt="lanzaderas" width="120px" /></a>
        </div>
    </div>

	<div class="col-md-12" style="padding:0 60px">

		<div class="col-md-9">
			<p style="font-size: 1.2em; padding:0 20px; text-align:justify;color:#005795">Este espacio contribuye a una mayor difusión de los perfiles profesionales de aquellas personas que han participado en la <strong>LANZADERA DE EMPLEO Y EMPRENDIMIENTO SOLIDARIO DEL AYUNTAMIENTO DE MEDIO CUDEYO</strong> (en registro, deberán firmar su consentimiento para publicar sus perfiles).
			Es propósito de este portal, facilitar que las empresas encuentren profesionales con talento, así como para que particulares encuentren los servicios que buscan en empresas y/o modelos de negocio, donde se puedan crear sinergias  entre profesionales. Haciendose visibles también se contribuye a una  mejor imagen del proyecto LEES.</p>
		</div>

		<div class="queson col-md-3">
			<!--<button type="button" class="btn" style="background-color:#3A3A3A; width:100%; margin:18px 20px; height:100px;"><a href="<?=Url::to('@web/img/queson_lanzaderas.png')?>" style="text-decoration:none; color:white; font-size:1.4em">¿Qué son las Lanzaderas?</a></button>-->
                         <?=Html::a(Yii::t('app','¿Qué son las Lanzaderas?'), ['/site/quesonlanzaderas'],['class' => 'btn','style' => 'background-color:#ccc; width:100%; margin:5px 20px;padding:40px 0px;color:black; font-size:1.4em;text-decoration:none']) ?>
		</div>	
	</div>

	<div class="fondo col-md-12" style="width: 100%; margin-top:40px;background:url(<?= $url ?>casacorpas3.png);background-size:cover">	
		<div class="col-md-12" style="margin-top:20px;">
			<p style="text-align:center; font-weight:bold; font-size:2.6em; font-family:serif; color:#3A3A3A; border-radius:20px; padding:6px 0">¿Estás Buscando Empresas o Talentos?</p>
			<p style="text-align:center; font-size:1.2em; font-weight:bold; padding:8px 0">Accede a toda la información relativa a los perfiles profesionales</p>
		</div>
                <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>
                        <?= $form->field($modelo, 'particular')->checkBox(['label' => 'particular','data-size'=>'small', 'class'=>'bs_switch','style'=>'margin-bottom:4px;', 'id'=>'particular']) ?>
                        <?= $form->field($modelo, 'empresa')->checkBox(['label' => 'empresa','data-size'=>'small', 'class'=>'bs_switch','style'=>'margin-bottom:4px;', 'id'=>'empresa']) ?>  
		<div class="col-md-12" style="display:flex; justify-content:center">
                    <div class=""  style="text-align:center;  border-radius:8px; margin-right:30px;padding:30px 0px">
				<!--<input type="radio" id="profesionales" name="" value="">-->
                        <div class="btn desmarcado" id="check_particular" style="background-color:#EB8448; text-decoration: none;color:black;width:100%;padding: 20px 50px;font-size: 1.3em ">
                           Encuentra profesionales
                        </div>
                    </div>
                       
                    <div class=""  style="text-align:center; padding:30px 0px">
			<div class="btn desmarcado" id="check_empresa" style="background-color:#C2C85C; text-decoration: none; color:black;width:100%;padding: 20px 50px;font-size: 1.3em">    
				Encuentra la empresa que necesitas
                        </div>
                    </div>    
		</div>

               
		<div class="col-md-12" style="padding: 30px 120px; display:flex; justify-content:center">
                    <div class="col-md-8">
                          <?= $form->field($modelo, 'textoBuscar')->textInput(['maxlength' => true,'placeholder' => 'Introduce el texto a buscar','class'=>'form-control','style'=>'width:100%;margin-left:29px']) ?>
                    </div>
                    <div class="col-md-4">
                        <?= Html::submitButton('Buscar', ['class' => 'btn btn-dark','style'=>'width:100%;font-weight:bold;margin-top:20px;margin-right:29px']) ?>
                    </div>
			   
		</div>
	
		<div class="col-md-12" style="margin-bottom:20px">
			<p style="font-size: 1.2em; padding:0 100px; text-align:justify">Las empresas interesadas en cualquiera de los pefiles profesionales de estas/os profesionales, también puden ponerse en contacto directamente a través de la Agencia de Desarrollo local del Ayuntamiento de Medio Cudeyo.</p>
			<p style="font-size: 1.2em; padding:0 100px; text-align:justify"><strong>Tlf: 942 522 833</strong></p>
			<p style="font-size: 1.2em; padding:0 100px; text-align:justify">Persona de contacto: Isabel Díaz (ADL).</p>
			<p style="font-size: 1.2em; padding:0 100px; text-align:justify">Las personas que han publicado sus perfiles profesionales en esta web que decidan darse de baja en este portal, deberán comunicarlo a la Agencia de Desarrollo Local del Ayuntamiento de Medio Cudeyo en el momento que se efectúe la baja.</p>
		</div>
	</div>
  
    <?php ActiveForm::end(); ?>
    
    
    </div>

     
           <?= ListView::widget([
                'dataProvider' => $dataProvider,
                'summary' => "",
                'itemView' => function ($model, $key, $index, $widget) {
                        return $this->render('_post',['model' => $model]);
                      },
                ]);     
    
    
    ?>
    
    <div class="pie col-md-12">
        <div class="textopie col-md-5">
                <p class="enelpie">Agencia de Desarrollo local del Ayuntamiento de Medio Cudeyo</p>
                <p class="enelpie">Tlf: 942 522 833</p>
        </div>
        <div class="gobierno col-md-3">
            <img src="<?=Url::to('@web/img/lg_gobierno2.png')?>" alt="gobierno" width="160px"/>
        </div>
        <div class="emcan col-md-2">
            <a href="https://www.empleacantabria.es/" target="_blank"><img src="<?=Url::to('@web/img/lg_emcan2.png')?>" alt="emcan" width="200px"/></a>
        </div>
        <div class="cantabria col-md-2">
            <img src="<?=Url::to('@web/img/lg_cantabria2.png')?>" alt="cantabria" width="150px"/>
        </div>
    </div>
    
 
</body>
</html>
<script>
$( document ).ready(function() {
//     $('button').attr('disabled','disabled');
//    $('#pertenece').change(function(event) { 
//
//    if ($('#pertenece').val() == 0){
//         $('#mensaje').css('display','none');
//    }else{
//         $('#mensaje').show();
//         $('input').attr('disabled','disabled');
//         $('checkbox').attr('disabled','disabled');
//         $('button').attr('disabled','disabled');
//         $('select').attr('disabled','disabled');
//    }
//
//    });
   
    $('#check_particular').click(function(event) {  
       
        var clase_ = $(this).hasClass("desmarcado");
        if(clase_){
          
            $(this).removeClass('desmarcado');
            $("#particular").prop('checked',true);
            
         }else{
            $(this).addClass('desmarcado');
            $("#particular").prop('checked',false);
        }

    });
    $('#check_empresa').click(function(event) {  
       
        var clase_ = $(this).hasClass("desmarcado");
        if(clase_){
          
            $(this).removeClass('desmarcado');
            $("#empresa").prop('checked',true);
            
         }else{
            $(this).addClass('desmarcado');
             $("#empresa").prop('checked',false);
        }

    });
     
}); 

</script>

views/site/register.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>


<div style="padding: 100px 200px">
    <h3><?= $msg ?></h3>
    <h1>Regístrate</h1>
    <?php $form = ActiveForm::begin([
        'method' => 'post',
     'id' => 'formulario',
     'enableClientValidation' => true,
     'enableAjaxValidation' => false,
    ]);
    ?>

    <div class="form-group">
     <?= $form->field($model, "username")->input("text")->label('Usuario') ?>   
    </div>

    <div class="form-group">
     <?= $form->field($model, "email")->input("email") ?>   
    </div>

    <div class="form-group">
     <?= $form->field($model, "password")->input("password")->label('Contraseña') ?>   
    </div>

    <div class="form-group">
     <?= $form->field($model, "password_repeat")->input("password")->label('Repite Contraseña') ?>   
    </div>

    <?= Html::submitButton("Registar", ["class" => "btn btn-primary"]) ?>

    <?php  ActiveForm::end(); ?>

</div>